services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "9229:9229"
    env_file:
      - ./back/.env.example
    volumes:
      - ./back:/app # Mounts the local ./back directory to /app in the container for live code updates
      # - /app/node_modules     # Ensures node_modules inside the container are not overwritten by the host
    depends_on:
      - redis

  redis:
    image: "redis:7-alpine"
    container_name: redis
    restart: unless-stopped
    # command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379" # Uncomment if you need host access
    labels:
      - "service=redis"

volumes:
  redis-data:
